Repository cowprotocol/services, pull requests merged in 2022-12, with the labels that each got.

#938 Separate Configuration For Limit Order Update Interval
  crates/autopilot/src/arguments.rs
  crates/autopilot/src/lib.rs
Labels: trivial

#989 Add Swapr Mainnet Liquidity
  crates/contracts/build.rs
  crates/shared/src/sources.rs
  crates/shared/src/sources/swapr.rs
Labels: trivial

#991 Include Uninternalized Settlement In Solver Competition Data
  crates/model/src/solver_competition.rs
  crates/orderbook/src/database/solver_competition.rs
  crates/solver/src/driver.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement/settlement_encoder.rs
Labels: external solver

#996 [Easy] rename part of the ethflow data api
  crates/e2e/tests/e2e/eth_flow.rs
  crates/model/src/order.rs
  crates/orderbook/openapi.yml
  crates/orderbook/src/database/orders.rs
  crates/shared/src/db_order_conversions.rs
Labels: trivial

#1002 API Scaffolding In `solvers` Binary
  Cargo.lock
  crates/solvers/Cargo.toml
  crates/solvers/openapi.yml
  crates/solvers/src/api/dto.rs
  crates/solvers/src/api/dto/auction.rs
  crates/solvers/src/api/dto/solution.rs
  crates/solvers/src/api/mod.rs
  crates/solvers/src/main.rs
  crates/solvers/src/util/mod.rs
  crates/solvers/src/util/serialize/hex.rs
  crates/solvers/src/util/serialize/mod.rs
  crates/solvers/src/util/serialize/u256.rs
Labels: colocation
