Repository cowprotocol/services, pull requests merged in 2022-11, with the labels that each got.

#702 Specify default whitelisted owners
  crates/shared/src/bad_token/token_owner_finder.rs
Labels: trivial

#706 Fix ParaSwap Trade Simulation Slippage
  crates/shared/src/trade_finding/paraswap.rs
Labels: trivial

#724 Reset trader approval
  crates/contracts/artifacts/Trader.json
  crates/contracts/solidity/Trader.sol
Labels: trivial

#727 Read All CLI Flags From Environment
  crates/autopilot/src/arguments.rs
  crates/driver/src/arguments.rs
  crates/orderbook/src/arguments.rs
  crates/shared/src/arguments.rs
  crates/shared/src/bad_token/token_owner_finder.rs
  crates/shared/src/ethrpc.rs
  crates/shared/src/http_client.rs
  crates/solver/src/arguments.rs
Labels: trivial

#737 Reuse now_in_epoch_seconds()
  Cargo.lock
  crates/refunder/Cargo.toml
  crates/refunder/src/refund_service.rs
  crates/solver/src/liquidity/uniswap_v3.rs
Labels: trivial

#774 Log Batched Buffered Requests
  crates/shared/src/ethrpc/buffered.rs
Labels: trivial

#772 Consider Limit Orders as User Orders
  crates/solver/src/analytics.rs
  crates/solver/src/driver.rs
  crates/solver/src/driver/solver_settlements.rs
  crates/solver/src/driver_logger.rs
  crates/solver/src/in_flight_orders.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement/settlement_encoder.rs
  crates/solver/src/settlement_ranker.rs
  crates/solver/src/solver/http_solver/settlement.rs
  crates/solver/src/solver/naive_solver/multi_order_solver.rs
Labels: limit orders

#785 Camel case for ethflow data in API
  crates/model/src/order.rs
  crates/orderbook/openapi.yml
Labels: trivial

#762 Prioritize orders in `SingleOrderSolvers`
  crates/solver/src/arguments.rs
  crates/solver/src/main.rs
  crates/solver/src/solver.rs
  crates/solver/src/solver/single_order_solver.rs
Labels: limit orders

#790 Unit Test With Limit Order Surplus
  crates/solver/src/settlement.rs
Labels: trivial, limit orders

#798 Add Support for Limit Order Buying Eth
  crates/model/src/order.rs
  crates/solver/src/liquidity/order_converter.rs
  crates/solver/src/settlement/settlement_encoder.rs
Labels: trivial, limit orders

#792 Include Full Fee Amount For Limit Orders
  crates/autopilot/src/database.rs
  crates/autopilot/src/database/onchain_order_events.rs
  crates/autopilot/src/database/orders.rs
  crates/autopilot/src/limit_order_quoter.rs
  crates/database/src/orders.rs
  crates/model/src/quote.rs
  crates/shared/src/order_quoting.rs
  crates/shared/src/order_validation.rs
Labels: limit orders

#799 Include Limit Order Buy Token Uniform Clearing Price
  crates/solver/src/settlement.rs
  crates/solver/src/settlement/settlement_encoder.rs
Labels: trivial, limit orders

#789 Refactor Warp Filter Initialization For Metrics Reset
  crates/driver/src/api.rs
  crates/orderbook/src/api.rs
  crates/orderbook/src/api/cancel_order.rs
  crates/orderbook/src/api/cancel_orders.rs
  crates/orderbook/src/api/get_auction.rs
  crates/orderbook/src/api/get_fee_and_quote.rs
  crates/orderbook/src/api/get_fee_info.rs
  crates/orderbook/src/api/get_markets.rs
  crates/orderbook/src/api/get_native_price.rs
  crates/orderbook/src/api/get_order_by_uid.rs
  crates/orderbook/src/api/get_orders_by_tx.rs
  crates/orderbook/src/api/get_solvable_orders.rs
  crates/orderbook/src/api/get_solvable_orders_v2.rs
  crates/orderbook/src/api/get_solver_competition.rs
  crates/orderbook/src/api/get_trades.rs
  crates/orderbook/src/api/get_user_orders.rs
  crates/orderbook/src/api/post_order.rs
  crates/orderbook/src/api/post_quote.rs
  crates/orderbook/src/api/post_solver_competition.rs
  crates/orderbook/src/api/replace_order.rs
  crates/shared/src/api.rs
Labels: oncall

#809 Migrate null surplus fees to 0 for limit orders
  database/sql/V043__surplus_fee_null.sql
Labels: trivial, limit orders

#800 Configuring refunder builds and auto-redeployments
  .github/workflows/deploy.yaml
  docker/Dockerfile.binary
Labels: trivial

#810 Handle ERC-1271 Signature Verification Reverts
  crates/shared/src/order_validation.rs
  crates/shared/src/signature_validator.rs
Labels: oncall

#823 Change Default Market Makable Token List
  crates/solver/src/arguments.rs
Labels: trivial

#821 Use `eth_call` For Fetching Current Block Header Information
  crates/autopilot/src/auction_transaction.rs
  crates/autopilot/src/lib.rs
  crates/autopilot/src/solvable_orders.rs
  crates/contracts/artifacts/FetchBlock.json
  crates/contracts/build.rs
  crates/contracts/solidity/FetchBlock.sol
  crates/contracts/solidity/Makefile
  crates/contracts/src/lib.rs
  crates/driver/src/driver.rs
  crates/shared/src/current_block.rs
  crates/shared/src/event_handling.rs
  crates/shared/src/macros.rs
  crates/shared/src/maintenance.rs
  crates/shared/src/recent_block_cache.rs
  crates/solver/src/driver.rs
Labels: oncall

#802 Filter Order With Insufficient Sell Amount
  crates/autopilot/src/solvable_orders.rs
Labels: limit orders

#834 Improve Order Creation Logging
  crates/orderbook/src/api/post_order.rs
  crates/orderbook/src/orderbook.rs
Labels: trivial

#845 Give metrics for token owner updates more specific name
  crates/shared/src/bad_token/token_owner_finder/solvers/solver_finder.rs
Labels: trivial

#847 Route version endpoint at `/v1/version` again
  crates/orderbook/src/api/version.rs
Labels: trivial

#853 Remove Rinkeby From OpenAPI Spec
  crates/orderbook/openapi.yml
Labels: trivial

#854 Drop Rinkeby from README.md
  README.md
Labels: trivial

#860 Improve Revert Error Detection
  Cargo.lock
  Cargo.toml
Labels: trivial
