Repository cowprotocol/services, pull requests merged in 2023-04, with the labels that each got.

#1419 Remove CIP20 transition code
  crates/solver/src/arguments.rs
  crates/solver/src/driver.rs
  crates/solver/src/run.rs
  crates/solver/src/settlement_ranker.rs
Labels: CIP20

#1435 Improve Limit Order Filtering Logging
  crates/autopilot/src/fok_limit_orders/quoter.rs
Labels: trivial

#1440 Relax PreSign Balance Exception
  crates/shared/src/order_validation.rs
Labels: trivial

#1441 No Simulation for Cancelled Settlement Transactions
  crates/solver/src/driver_logger.rs
  crates/solver/src/settlement_submission.rs
Labels: trivial, oncall

#1442 Add Rate Limiting Support to Single Order Solvers
  crates/shared/src/paraswap_api.rs
  crates/solver/src/solver/balancer_sor_solver.rs
  crates/solver/src/solver/oneinch_solver.rs
  crates/solver/src/solver/paraswap_solver.rs
  crates/solver/src/solver/single_order_solver.rs
  crates/solver/src/solver/zeroex_solver.rs
Labels: oncall

#1452 Adjust the simulation block number
  crates/shared/src/http_solver/model.rs
  crates/solver/src/settlement_rater.rs
Labels: external solver

#1454 Fix new clippy warnings
  crates/refunder/src/refund_service.rs
  crates/shared/src/api.rs
  crates/shared/src/balancer_sor_api.rs
  crates/shared/src/http_solver/model.rs
  crates/shared/src/subgraph.rs
  crates/solver/src/solver/optimizing_solver.rs
Labels: trivial

#1458 Adjust score calculator for reverts
  crates/solver/src/solver/score_computation.rs
Labels: CIP20

#1462 Enable quote predictions for native price estimator
  crates/shared/src/price_estimation/factory.rs
Labels: trivial
