Repository cowprotocol/services, pull requests merged in 2023-05, with the labels that each got.

#1463 Stop Rate Limited Single Order Solver
  crates/solver/src/solver/single_order_solver.rs
Labels: trivial, oncall

#1479 Additional Autopilot Logs
  crates/autopilot/src/solvable_orders.rs
Labels: trivial

#1488 Promote log to debug
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/solver/src/settlement_post_processing/mod.rs
  crates/solver/src/settlement_post_processing/optimize_score.rs
Labels: trivial

#1486 Add CLI arg for allowing orders with custom interactions
  crates/orderbook/src/arguments.rs
  crates/orderbook/src/run.rs
  crates/shared/src/order_validation.rs
Labels: custom-interactions

#1482 Read write post interactions in db
  crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
  crates/autopilot/src/driver_model.rs
  crates/autopilot/src/run_loop.rs
  crates/database/src/orders.rs
  crates/driver/src/boundary/settlement.rs
  crates/driver/src/domain/competition/order/mod.rs
  crates/driver/src/domain/quote.rs
  crates/driver/src/infra/api/routes/solve/dto/auction.rs
  crates/driver/src/tests/cases/buy_eth.rs
  crates/driver/src/tests/cases/limit_order/buy.rs
  crates/driver/src/tests/cases/limit_order/sell.rs
  crates/driver/src/tests/cases/solver_balance.rs
  crates/driver/src/tests/cases/verify_asset_flow/limit.rs
  crates/driver/src/tests/cases/verify_asset_flow/liquidity.rs
  crates/driver/src/tests/cases/verify_asset_flow/market.rs
  crates/driver/src/tests/setup/new/driver.rs
  crates/model/src/order.rs
  crates/orderbook/src/database/orders.rs
  crates/shared/src/db_order_conversions.rs
  crates/solvers/src/tests/legacy/jit_order.rs
  database/sql/V050__add_interaction_execution_time.sql
Labels: custom-interactions

#1485 Encode post interactions
  crates/solver/src/settlement/settlement_encoder.rs
Labels: custom-interactions

#1517 Better error messages when failing to retrieve Balancer factory
  crates/shared/src/sources/balancer_v2/pool_fetching.rs
Labels: oncall

#1519 Do not consider single order solver failures when there is no match
  crates/solver/src/solver/oneinch_solver.rs
  crates/solver/src/solver/paraswap_solver.rs
  crates/solver/src/solver/single_order_solver.rs
Labels: oncall

#1522 [Logging] Improve single order solver logs
  crates/solver/src/driver.rs
  crates/solver/src/solver/single_order_solver.rs
Labels: oncall

#1536 Fix Wrong Owner Message to Include Full Address
  crates/orderbook/src/api/post_order.rs
Labels: trivial

#1425 Save competition in autopilot
  Cargo.lock
  crates/autopilot/src/arguments.rs
  crates/autopilot/src/database.rs
  crates/autopilot/src/database/competition.rs
  crates/autopilot/src/database/on_settlement_event_updater.rs
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/driver_model.rs
  crates/autopilot/src/lib.rs
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/autopilot/src/run_loop.rs
  crates/database/src/auction_prices.rs
  crates/database/src/order_execution.rs
  crates/database/src/orders.rs
  crates/driver/Cargo.toml
  crates/driver/src/boundary/settlement.rs
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/competition/order/mod.rs
  crates/driver/src/domain/competition/solution/mod.rs
  crates/driver/src/domain/competition/solution/settlement.rs
  crates/driver/src/infra/api/routes/quote/dto/quote.rs
  crates/driver/src/infra/api/routes/quote/mod.rs
  crates/driver/src/infra/api/routes/solve/dto/auction.rs
  crates/driver/src/infra/api/routes/solve/dto/solution.rs
  crates/driver/src/infra/api/routes/solve/mod.rs
  crates/driver/src/infra/config/file/load.rs
  crates/driver/src/infra/solver/dto/auction.rs
  crates/driver/src/infra/solver/dto/solution.rs
  crates/driver/src/infra/solver/mod.rs
  crates/driver/src/tests/cases/buy_eth.rs
  crates/driver/src/tests/cases/limit_order/buy.rs
  crates/driver/src/tests/cases/limit_order/sell.rs
  crates/driver/src/tests/cases/merge_settlements.rs
  crates/driver/src/tests/cases/mod.rs
  crates/driver/src/tests/cases/multiple_solutions.rs
  crates/driver/src/tests/cases/negative_scores.rs
  crates/driver/src/tests/cases/quote.rs
  crates/driver/src/tests/cases/risk.rs
  crates/driver/src/tests/cases/settle.rs
  crates/driver/src/tests/cases/solve.rs
  crates/driver/src/tests/cases/solver_balance.rs
  crates/driver/src/tests/cases/verify_asset_flow/limit.rs
  crates/driver/src/tests/cases/verify_asset_flow/liquidity.rs
  crates/driver/src/tests/cases/verify_asset_flow/market.rs
  crates/driver/src/tests/cases/verify_internalization.rs
  crates/driver/src/tests/setup/new/blockchain.rs
  crates/driver/src/tests/setup/new/driver.rs
  crates/driver/src/tests/setup/new/mod.rs
  crates/driver/src/tests/setup/new/solver.rs
  crates/solvers/src/api/dto/auction.rs
Labels: colocation, CIP20
