Repository cowprotocol/services, pull requests merged in 2023-07, with the labels that each got.

#1636 Uniform Caching of 1Inch Spender
  crates/autopilot/src/solvable_orders.rs
  crates/e2e/tests/e2e/eth_flow.rs
  crates/shared/src/arguments.rs
  crates/shared/src/oneinch_api.rs
  crates/shared/src/price_estimation/competition.rs
  crates/shared/src/trade_finding/oneinch.rs
  crates/solver/src/solver/oneinch_solver.rs
  crates/solvers/src/infra/dex/oneinch/mod.rs
Labels: oncall

#1639 Filter Out Invalid Uniswap V2 Pools
  crates/driver/src/boundary/liquidity/mod.rs
  crates/driver/src/boundary/liquidity/uniswap/v2.rs
  crates/solvers/src/api/dto/auction.rs
  crates/solvers/src/api/mod.rs
  crates/solvers/src/domain/liquidity/constant_product.rs
Labels: oncall

#1650 Fix Copy-Pasta Error From #1649
  crates/e2e/tests/e2e/quoting.rs
Labels: trivial

#1648 Fix solver HTTP timeout bug
  crates/driver/src/domain/competition/auction.rs
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/competition/solution/mod.rs
  crates/driver/src/domain/quote.rs
  crates/driver/src/infra/solver/mod.rs
  crates/driver/src/tests/setup/solver.rs
Labels: bug, colocation

#1651 `driver`: Don't wait for tx confirmation in `/settle`
  crates/driver/example.toml
  crates/driver/src/boundary/mempool.rs
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/eth/mod.rs
  crates/driver/src/domain/mempools.rs
  crates/driver/src/domain/mod.rs
  crates/driver/src/infra/api/error.rs
  crates/driver/src/infra/api/mod.rs
  crates/driver/src/infra/mempool/mod.rs
  crates/driver/src/infra/observe/mod.rs
  crates/driver/src/run.rs
Labels: bug, colocation

#1653 Send Order Interactions To Colocated Driver
  crates/autopilot/src/driver_model.rs
  crates/autopilot/src/run_loop.rs
  crates/driver/openapi.yml
  crates/driver/src/domain/mempools.rs
  crates/driver/src/infra/observe/mod.rs
  crates/e2e/tests/e2e/colocation_hooks.rs
  crates/e2e/tests/e2e/hooks.rs
  crates/e2e/tests/e2e/main.rs
Labels: trivial

#1654 Make App Data Size Limit Configurable
  crates/orderbook/src/arguments.rs
  crates/orderbook/src/run.rs
  crates/shared/src/app_data.rs
Labels: trivial

#1661 Pass token info to `driver`
  crates/autopilot/src/driver_model.rs
  crates/autopilot/src/lib.rs
  crates/autopilot/src/run_loop.rs
  crates/driver/src/domain/competition/auction.rs
  crates/driver/src/infra/api/routes/solve/dto/auction.rs
Labels: bug, colocation

#1689 Notify solvers about submission result
  crates/shared/src/http_solver/model.rs
  crates/solver/src/driver.rs
Labels: external solver

#1701 Add Driver Support for Balancer V2 Weighted Pools
  Cargo.lock
  crates/driver/Cargo.toml
  crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
  crates/driver/src/boundary/liquidity/balancer/v2/weighted.rs
  crates/driver/src/boundary/settlement.rs
  crates/driver/src/domain/competition/solution/interaction.rs
  crates/driver/src/domain/liquidity/balancer/v2/mod.rs
  crates/driver/src/domain/liquidity/balancer/v2/weighted.rs
  crates/driver/src/infra/config/file/mod.rs
  crates/driver/src/infra/solver/dto/auction.rs
  crates/driver/src/infra/solver/mod.rs
  crates/shared/src/sources/balancer_v2/pool_fetching.rs
  crates/solver/src/interactions/balancer_v2.rs
  crates/solver/src/liquidity/balancer_v2.rs
Labels: colocation

#1702 Add Driver Support for Balancer V2 Stable Pools
  crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
  crates/driver/src/boundary/liquidity/balancer/v2/stable.rs
  crates/driver/src/boundary/liquidity/balancer/v2/weighted.rs
  crates/driver/src/boundary/settlement.rs
  crates/driver/src/domain/competition/solution/interaction.rs
  crates/driver/src/domain/liquidity/balancer/v2/stable.rs
  crates/driver/src/infra/solver/dto/auction.rs
  crates/shared/src/sources/balancer_v2/pools/stable.rs
  crates/solver/src/liquidity.rs
  crates/solver/src/liquidity/balancer_v2.rs
  crates/solver/src/settlement_simulation.rs
  crates/solver/src/solver.rs
  crates/solver/src/solver/http_solver/instance_creation.rs
  crates/solver/src/solver/http_solver/settlement.rs
Labels: colocation

#1717 Update App Data Error Strings
  crates/orderbook/src/app_data.rs
Labels: trivial
