Repository cowprotocol/services, pull requests merged in 2023-08, with the labels that each got.

#1740 Revert "Query the graph in smaller chunks (#1719)"
  crates/autopilot/src/lib.rs
  crates/shared/src/sources/balancer_v2/graph_api.rs
  crates/shared/src/subgraph.rs
Labels: trivial

#1688 Get surplus_fee from solvers for FOK limit orders
  crates/autopilot/src/database/competition.rs
  crates/autopilot/src/database/on_settlement_event_updater.rs
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/driver_model.rs
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/autopilot/src/run_loop.rs
  crates/autopilot/src/solvable_orders.rs
  crates/database/src/order_execution.rs
  crates/database/src/orders.rs
  crates/driver/src/domain/competition/order/mod.rs
  crates/driver/src/domain/competition/solution/trade.rs
  crates/driver/src/infra/api/routes/solve/dto/auction.rs
  crates/driver/src/infra/solver/dto/auction.rs
  crates/driver/src/tests/cases/asset_flow.rs
  crates/driver/src/tests/cases/mod.rs
  crates/driver/src/tests/cases/settle.rs
  crates/driver/src/tests/setup/driver.rs
  crates/driver/src/tests/setup/mod.rs
  crates/driver/src/tests/setup/solver.rs
  crates/model/src/order.rs
  crates/solver/src/liquidity.rs
  crates/solver/src/liquidity/order_converter.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement/settlement_encoder.rs
  crates/solver/src/solver/http_solver/settlement.rs
  crates/solver/src/solver/naive_solver.rs
  crates/solvers/src/boundary/naive.rs
  crates/solvers/src/domain/order.rs
  crates/solvers/src/domain/solution.rs
Labels: external solver, limit orders

#1755 Add helpful steps for on-call in error message
  crates/autopilot/src/lib.rs
  crates/orderbook/src/run.rs
  crates/solver/src/run.rs
Labels: trivial

#1777 Pretty format gas price
  Cargo.lock
  Cargo.toml
  crates/solver/src/driver.rs
  crates/solver/src/settlement_submission/submitter.rs
Labels: trivial

#1798 Delete `codecov.yml`.
  codecov.yml
Labels: trivial

#1778 Refactor ERC-20 Interactions in Driver
  crates/driver/src/boundary/quote.rs
  crates/driver/src/boundary/settlement.rs
  crates/driver/src/domain/competition/solution/interaction.rs
  crates/driver/src/domain/competition/solution/mod.rs
  crates/driver/src/domain/eth/allowance.rs
  crates/driver/src/infra/blockchain/mod.rs
  crates/driver/src/infra/blockchain/token.rs
  crates/driver/src/infra/solver/dto/solution.rs
  crates/driver/src/infra/tokens.rs
Labels: trivial

#1808 Fix clippy warnings for Rust 1.72.0
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/e2e/src/setup/services.rs
  crates/model/src/quote.rs
  crates/shared/src/account_balances/cached.rs
  crates/shared/src/account_balances/web3.rs
  crates/shared/src/baseline_solver.rs
  crates/shared/src/event_handling.rs
  crates/shared/src/sources/balancer_v2/swap/stable_math.rs
  crates/shared/src/sources/uniswap_v3/pool_fetching.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement/settlement_encoder.rs
  crates/solver/src/solver/http_solver/buffers.rs
  crates/solver/src/solver/naive_solver.rs
  crates/solver/src/solver/single_order_solver.rs
Labels: trivial

#1809 Remove obsolete BlockRetriever strategies
  crates/driver/src/boundary/liquidity/mod.rs
  crates/shared/src/current_block.rs
  crates/shared/src/current_block/arguments.rs
  crates/shared/src/current_block/eth_call.rs
  crates/shared/src/current_block/retriever.rs
Labels: trivial

#1806 Add Composable Stable Pool Contracts
  crates/contracts/artifacts/BalancerV2ComposableStablePool.json
  crates/contracts/artifacts/BalancerV2ComposableStablePoolFactory.json
  crates/contracts/artifacts/BalancerV2ComposableStablePoolFactoryV3.json
  crates/contracts/artifacts/BalancerV2ComposableStablePoolFactoryV4.json
  crates/contracts/artifacts/BalancerV2ComposableStablePoolFactoryV5.json
  crates/contracts/build.rs
  crates/contracts/src/bin/vendor.rs
  crates/contracts/src/lib.rs
Labels: trivial

#1815 Update `HooksTrampoline` Address
  crates/contracts/build.rs
Labels: trivial

#1687 `driver`: filter orders based on user balances
  crates/driver/src/domain/competition/auction.rs
  crates/driver/src/domain/competition/order/mod.rs
  crates/driver/src/domain/quote.rs
  crates/driver/src/infra/api/error.rs
  crates/driver/src/infra/api/routes/solve/dto/auction.rs
  crates/driver/src/infra/api/routes/solve/mod.rs
  crates/driver/src/infra/blockchain/contracts.rs
  crates/driver/src/infra/config/file/load.rs
  crates/driver/src/infra/config/file/mod.rs
  crates/driver/src/infra/observe/mod.rs
  crates/driver/src/tests/cases/mod.rs
  crates/driver/src/tests/cases/order_prioritization.rs
  crates/driver/src/tests/cases/order_sorting.rs
  crates/driver/src/tests/setup/blockchain.rs
  crates/driver/src/tests/setup/mod.rs
  crates/driver/src/tests/setup/solver.rs
Labels: colocation
