Repository cowprotocol/services, pull requests merged in 2023-03, with the labels that each got.

#1279 Cip20 Implementation
  Cargo.lock
  crates/autopilot/Cargo.toml
  crates/autopilot/src/arguments.rs
  crates/autopilot/src/auction_transaction.rs
  crates/autopilot/src/database.rs
  crates/autopilot/src/database/auction_prices.rs
  crates/autopilot/src/database/auction_transaction.rs
  crates/autopilot/src/database/on_settlement_event_updater.rs
  crates/autopilot/src/database/orders.rs
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/lib.rs
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/database/src/auction_participants.rs
  crates/database/src/auction_prices.rs
  crates/database/src/auction_transaction.rs
  crates/database/src/events.rs
  crates/database/src/lib.rs
  crates/database/src/settlement_observations.rs
  crates/database/src/settlement_scores.rs
  crates/database/src/settlements.rs
  crates/driver/src/boundary/quote.rs
  crates/driver/src/boundary/settlement.rs
  crates/e2e/tests/e2e/setup/services.rs
  crates/model/src/solver_competition.rs
  crates/orderbook/src/database/solver_competition.rs
  crates/shared/src/arguments.rs
  crates/shared/src/external_prices.rs
  crates/shared/src/http_solver/model.rs
  crates/shared/src/lib.rs
  crates/shared/src/macros.rs
  crates/solver/src/arguments.rs
  crates/solver/src/driver.rs
  crates/solver/src/driver/solver_settlements.rs
  crates/solver/src/driver_logger.rs
  crates/solver/src/liquidity/slippage.rs
  crates/solver/src/objective_value.rs
  crates/solver/src/run.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement_ranker.rs
  crates/solver/src/settlement_rater.rs
  crates/solver/src/solver.rs
  crates/solver/src/solver/http_solver/instance_creation.rs
  crates/solver/src/solver/naive_solver.rs
  crates/solver/src/solver/naive_solver/multi_order_solver.rs
  crates/solver/src/solver/single_order_solver.rs
  crates/solver/src/solver/single_order_solver/merge.rs
  crates/solver/src/solver/zeroex_solver.rs
  crates/solvers/src/boundary/naive.rs
  database/sql/V048__create_settlement_rewards.sql
Labels: solver rewards

#1297 SolverRewards 10: Fix score sorting
  crates/solver/src/driver.rs
Labels: solver rewards

#1299 SolverRewards 11: Sort settlements by ranking
  crates/solver/src/driver.rs
Labels: solver rewards

#1301 SolverRewards: Add temporary logs
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/on_settlement_event_updater.rs
Labels: solver rewards

#1303 Store executed solver fee
  crates/autopilot/src/database/orders.rs
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/lib.rs
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/database/src/order_execution.rs
  crates/database/src/orders.rs
  crates/model/src/solver_competition.rs
  crates/orderbook/src/database/orders.rs
  crates/orderbook/src/database/solver_competition.rs
  crates/solver/src/driver.rs
  database/sql/V049__add_full_fee_amount.sql
Labels: solver rewards

#1332 Activate auction rewards based on timestamp
  crates/solver/src/arguments.rs
  crates/solver/src/driver.rs
  crates/solver/src/run.rs
  crates/solver/src/settlement_ranker.rs
Labels: solver rewards

#1342 CIP20 move activation date
  crates/solver/src/arguments.rs
Labels: trivial, solver rewards

#1308 SolverRewards: Gnosis solvers score
  crates/driver/src/boundary/settlement.rs
  crates/shared/src/http_solver/model.rs
  crates/solver/src/arguments.rs
  crates/solver/src/objective_value.rs
  crates/solver/src/run.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement_post_processing/mod.rs
  crates/solver/src/settlement_post_processing/optimize_buffer_usage.rs
  crates/solver/src/settlement_post_processing/optimize_score.rs
  crates/solver/src/settlement_post_processing/optimize_unwrapping.rs
  crates/solver/src/settlement_rater.rs
  crates/solver/src/solver.rs
  crates/solver/src/solver/optimizing_solver.rs
  crates/solver/src/solver/score_computation.rs
  crates/solver/src/solver/single_order_solver.rs
  crates/solver/src/solver/zeroex_solver.rs
Labels: solver rewards

#1349 CIP20: Forward score to settlement creation
  crates/solver/src/solver/http_solver/settlement.rs
Labels: solver rewards

#1353 CIP20: Filter out non-positive score settlements
  crates/shared/src/http_solver/model.rs
  crates/solver/src/arguments.rs
  crates/solver/src/driver.rs
  crates/solver/src/metrics.rs
  crates/solver/src/run.rs
  crates/solver/src/settlement_ranker.rs
Labels: solver rewards

#1354 Fix bumping the gas price for simulation
  crates/solver/src/settlement_access_list.rs
  crates/solver/src/settlement_ranker.rs
  crates/solver/src/settlement_rater.rs
  crates/solver/src/settlement_simulation.rs
  crates/solver/src/settlement_submission/dry_run.rs
Labels: oncall

#1362 Make Driver EIP-1559 Aware
  crates/driver/src/boundary/settlement.rs
  crates/driver/src/domain/competition/auction.rs
  crates/driver/src/domain/eth/gas.rs
  crates/driver/src/domain/eth/mod.rs
  crates/driver/src/domain/quote.rs
  crates/driver/src/infra/blockchain/mod.rs
  crates/driver/src/infra/solver/dto/auction.rs
  crates/driver/src/tests/cases/limit_order/buy.rs
  crates/driver/src/tests/cases/limit_order/sell.rs
  crates/driver/src/tests/cases/quote.rs
  crates/driver/src/tests/cases/settle.rs
  crates/driver/src/tests/cases/solve.rs
  crates/driver/src/tests/cases/verify_asset_flow/limit.rs
  crates/driver/src/tests/cases/verify_asset_flow/liquidity.rs
  crates/driver/src/tests/cases/verify_asset_flow/market.rs
  crates/driver/src/tests/cases/verify_internalization.rs
  crates/driver/src/tests/setup/blockchain/mod.rs
Labels: ddd

#1369 Add Unit Tests for Submitter Estimator
  crates/solver/src/settlement_submission/submitter.rs
Labels: trivial

#1372 Don't Error on Partially Fillable Limit Order Missing Surplus Fee
  crates/solver/src/liquidity/order_converter.rs
Labels: trivial

#1371 Add Example Legacy Solver Adapter Configuration
  crates/solvers/config/example.legacy.toml
Labels: documentation, trivial

#1373 Crash on Failed UniV3 Initialization
  crates/autopilot/src/lib.rs
  crates/orderbook/src/run.rs
  crates/solver/src/run.rs
Labels: oncall

#1381 Fix Co-located Solver Response Format
  crates/solvers/config/example.zeroex.toml
  crates/solvers/src/api/dto/solution.rs
  crates/solvers/src/infra/config/dex/file.rs
  crates/solvers/src/tests/balancer/market_order.rs
  crates/solvers/src/tests/dex/partial_fill.rs
  crates/solvers/src/tests/legacy/attaching_approvals.rs
  crates/solvers/src/tests/legacy/jit_order.rs
  crates/solvers/src/tests/zeroex/market_order.rs
  crates/solvers/src/tests/zeroex/options.rs
Labels: trivial

#1351 CIP20: Improve score calculation logging
  crates/solver/src/driver_logger.rs
  crates/solver/src/settlement_post_processing/optimize_score.rs
  crates/solver/src/solver/score_computation.rs
Labels: solver rewards

#1383 Remove rest of order maturity
  crates/shared/src/http_solver/model.rs
Labels: trivial

#1384 Improve WETH Handling in Legacy Adapter
  crates/solvers/src/boundary/legacy.rs
  crates/solvers/src/tests/legacy/attaching_approvals.rs
  crates/solvers/src/tests/legacy/concentrated_liquidity.rs
  crates/solvers/src/tests/legacy/jit_order.rs
  crates/solvers/src/tests/legacy/market_order.rs
Labels: trivial

#1385 Add Solver Fee Fields to DTOs
  crates/driver/src/infra/solver/dto/solution.rs
  crates/shared/src/http_solver/model.rs
  crates/shared/src/price_estimation/http.rs
  crates/solver/src/solver/http_solver/settlement.rs
  crates/solvers/openapi.yml
Labels: trivial

#1392 Extend SingleOrderSolver Interface With Gas Estimate
  crates/solver/src/solver/balancer_sor_solver.rs
  crates/solver/src/solver/oneinch_solver.rs
  crates/solver/src/solver/paraswap_solver.rs
  crates/solver/src/solver/single_order_solver.rs
  crates/solver/src/solver/zeroex_solver.rs
Labels: trivial

#1395 E2E Test With Legacy Solver
  crates/e2e/tests/e2e/partially_fillable.rs
Labels: trivial

#1399 CIP20: Filter out too high scores
  crates/shared/src/http_solver/model.rs
  crates/solver/src/settlement_ranker.rs
Labels: CIP20

#1404 Increase partial fill attempt after success
  crates/solver/src/solver/single_order_solver.rs
  crates/solver/src/solver/single_order_solver/fills.rs
  crates/solvers/src/domain/solver/dex/fills.rs
  crates/solvers/src/domain/solver/dex/solver.rs
  crates/solvers/src/tests/dex/partial_fill.rs
Labels: partial-fill
