Repository cowprotocol/services, pull requests merged in 2023-10, with the labels that each got.

#1916 Avoid Collecting Driver Solutions in RunLoop
  crates/autopilot/src/run_loop.rs
Labels: trivial

#1922 Remove not used arguments
  crates/shared/src/price_estimation.rs
Labels: trivial

#1935 fix: openapi typo
  crates/orderbook/openapi.yml
Labels: bug

#1940 Reduce Error-ness of not Finding Solutions
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/infra/api/error.rs
  crates/driver/src/infra/api/routes/solve/dto/solved.rs
  crates/driver/src/infra/observe/mod.rs
  crates/driver/src/tests/cases/asset_flow.rs
  crates/driver/src/tests/cases/internalization.rs
  crates/driver/src/tests/cases/negative_scores.rs
  crates/driver/src/tests/cases/settle.rs
  crates/driver/src/tests/cases/solver_balance.rs
  crates/driver/src/tests/setup/blockchain.rs
  crates/driver/src/tests/setup/mod.rs
Labels: trivial

#1958 Fix solver slippage parsing
  crates/driver/src/infra/config/file/load.rs
  crates/solvers/src/infra/config/dex/file.rs
Labels: E:3.1 Driver Colocation

#1994 Make times between auction run_loops configurable
  crates/autopilot/src/run_loop.rs
Labels: E:3.1 Driver Colocation
