Repository cowprotocol/services, pull requests merged in 2023-02, with the labels that each got.

#1191 Fix duration overflow bug
  crates/shared/src/rate_limiter.rs
Labels: bug

#1204 New tracing logs for debugging Paraswap
  crates/shared/src/paraswap_api.rs
Labels: trivial

#1225 Bump Ethcontract To Improve Nethermind Revert Detection
  Cargo.lock
  Cargo.toml
Labels: trivial

#1173 CIP-17 ranking with score
  crates/e2e/tests/e2e/limit_orders.rs
  crates/e2e/tests/e2e/onchain_settlement.rs
  crates/e2e/tests/e2e/services.rs
  crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
  crates/e2e/tests/e2e/smart_contract_orders.rs
  crates/e2e/tests/e2e/vault_balances.rs
  crates/model/src/solver_competition.rs
  crates/orderbook/src/database/solver_competition.rs
  crates/shared/src/http_solver/model.rs
  crates/solver/src/arguments.rs
  crates/solver/src/driver.rs
  crates/solver/src/driver/solver_settlements.rs
  crates/solver/src/driver_logger.rs
  crates/solver/src/main.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement_ranker.rs
  crates/solver/src/settlement_rater.rs
Labels: solver rewards

#1232 Force Hardhat to Bind to 127.0.0.1
  .github/workflows/pull-request.yaml
Labels: trivial

#1253 Generic DEX Solver
  crates/solvers/src/domain/dex/mod.rs
  crates/solvers/src/domain/order.rs
  crates/solvers/src/domain/solver/balancer.rs
  crates/solvers/src/domain/solver/dex.rs
  crates/solvers/src/domain/solver/mod.rs
  crates/solvers/src/infra/dex/mod.rs
  crates/solvers/src/run.rs
  crates/solvers/src/util/fmt/mod.rs
Labels: ddd

#1256 SolverRewards 1: Move out ExternalPrices
  crates/driver/src/boundary/quote.rs
  crates/driver/src/boundary/settlement.rs
  crates/shared/src/external_prices.rs
  crates/shared/src/lib.rs
  crates/shared/src/macros.rs
  crates/solver/src/driver.rs
  crates/solver/src/liquidity/slippage.rs
  crates/solver/src/objective_value.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement_ranker.rs
  crates/solver/src/settlement_rater.rs
  crates/solver/src/solver.rs
  crates/solver/src/solver/http_solver/instance_creation.rs
  crates/solver/src/solver/naive_solver/multi_order_solver.rs
  crates/solver/src/solver/single_order_solver.rs
  crates/solver/src/solver/single_order_solver/merge.rs
  crates/solver/src/solver/zeroex_solver.rs
Labels: solver rewards

#1258 SolverRewards 2: DecodedSettlement implementation
  Cargo.lock
  crates/autopilot/Cargo.toml
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/lib.rs
Labels: solver rewards

#1267 Use Obviously Wrong Private Keys in Example Config
  crates/driver/example.toml
Labels: trivial

#1263 SolverRewards 3: Updated db schema and read/write functions
  crates/database/src/auction_participants.rs
  crates/database/src/auction_prices.rs
  crates/database/src/auction_transaction.rs
  crates/database/src/events.rs
  crates/database/src/lib.rs
  crates/database/src/settlement_observations.rs
  crates/database/src/settlement_scores.rs
  crates/database/src/settlements.rs
  database/sql/V048__create_settlement_rewards.sql
Labels: solver rewards

#1270 SolverRewards 4: Populate scores and participants
  crates/autopilot/src/arguments.rs
  crates/autopilot/src/lib.rs
  crates/database/src/auction_participants.rs
  crates/database/src/settlement_scores.rs
  crates/database/src/settlements.rs
  crates/e2e/tests/e2e/limit_orders.rs
  crates/e2e/tests/e2e/onchain_settlement.rs
  crates/e2e/tests/e2e/services.rs
  crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
  crates/e2e/tests/e2e/smart_contract_orders.rs
  crates/e2e/tests/e2e/vault_balances.rs
  crates/model/src/solver_competition.rs
  crates/orderbook/src/database/solver_competition.rs
  crates/shared/src/arguments.rs
  crates/solver/src/arguments.rs
  crates/solver/src/driver.rs
  crates/solver/src/main.rs
  database/sql/V048__create_settlement_rewards.sql
Labels: solver rewards

#1274 Fix balancer parsing error
  crates/shared/src/balancer_sor_api.rs
  crates/solvers/src/infra/dex/balancer/dto.rs
Labels: oncall

#1271 SolverRewards 5: Populate observations and auction prices
  crates/autopilot/src/auction_transaction.rs
  crates/autopilot/src/database.rs
  crates/autopilot/src/database/auction_prices.rs
  crates/autopilot/src/database/auction_transaction.rs
  crates/autopilot/src/database/on_settlement_event_updater.rs
  crates/autopilot/src/database/orders.rs
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/lib.rs
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/autopilot/src/solvable_orders.rs
  crates/database/src/auction_prices.rs
  crates/database/src/events.rs
  crates/database/src/settlement_observations.rs
  crates/solver/src/driver/solver_settlements.rs
  crates/solver/src/driver_logger.rs
  crates/solver/src/run.rs
  crates/solver/src/settlement.rs
  crates/solver/src/settlement_ranker.rs
  crates/solver/src/solver/naive_solver.rs
  crates/solvers/src/boundary/naive.rs
  database/sql/V048__create_settlement_rewards.sql
Labels: solver rewards

#1283 SolverRewards 7: Fix sql comments and formating
  database/sql/V048__create_settlement_rewards.sql
Labels: trivial, solver rewards

#1282 SolverRewards 6: Populate external prices from driver
  crates/autopilot/src/database/auction_prices.rs
  crates/autopilot/src/database/on_settlement_event_updater.rs
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/autopilot/src/solvable_orders.rs
  crates/database/src/auction_prices.rs
  crates/model/src/solver_competition.rs
  crates/orderbook/src/database/solver_competition.rs
  crates/shared/src/http_solver/model.rs
  crates/solver/src/driver.rs
  crates/solver/src/settlement_rater.rs
Labels: solver rewards

#1284 SolverRewards 8: Fix executed amount for fee calculation
  crates/autopilot/src/decoded_settlement.rs
  crates/autopilot/src/on_settlement_event_updater.rs
Labels: solver rewards
