Repository cowprotocol/services, pull requests merged in 2023-01, with the labels that each got.

#1018 Log Closed Orders in Alerter
  crates/alerter/src/main.rs
Labels: trivial

#1094 Upload Auction Instance JSON with Gzip Content Encoding
  crates/solver/src/s3_instance_upload.rs
  crates/solver/src/solver/http_solver/instance_cache.rs
Labels: trivial

#1118 Add `driver` and `solvers` to Docker Image
  docker/Dockerfile.binary
Labels: trivial

#1106 Encode solution ID in the settlement
  crates/driver/src/boundary/mempool.rs
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/competition/solution/mod.rs
  crates/driver/src/domain/competition/solution/settlement.rs
  crates/driver/src/infra/solver/dto/solution.rs
  crates/driver/src/tests/cases/settle.rs
  crates/driver/src/tests/cases/solve.rs
  crates/solver/src/settlement_submission.rs
  crates/solver/src/settlement_submission/submitter.rs
Labels: colocation

#1121 Parallelize the driver tests
  .gitignore
  Cargo.lock
  crates/dev-geth/Cargo.toml
  crates/dev-geth/src/main.rs
  crates/driver/src/tests/cases/example_config.rs
  crates/driver/src/tests/cases/mod.rs
  crates/driver/src/tests/cases/quote.rs
  crates/driver/src/tests/cases/settle.rs
  crates/driver/src/tests/cases/solve.rs
  crates/driver/src/tests/setup/blockchain/mod.rs
  crates/driver/src/tests/setup/blockchain/uniswap.rs
  crates/driver/src/tests/setup/driver.rs
  crates/solver/src/objective_value.rs
  docker-compose.yaml
  docker/Dockerfile.dev-geth
  docker/base-datadir.tar
Labels: colocation

#1124 Use config file instead of CLI args for `driver`
  crates/driver/example.toml
  crates/driver/src/boundary/mempool.rs
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/eth/mod.rs
  crates/driver/src/infra/api/mod.rs
  crates/driver/src/infra/config/cli.rs
  crates/driver/src/infra/config/file.rs
  crates/driver/src/infra/config/file/load.rs
  crates/driver/src/infra/config/file/mod.rs
  crates/driver/src/infra/config/mod.rs
  crates/driver/src/infra/mempool/mod.rs
  crates/driver/src/infra/mod.rs
  crates/driver/src/infra/simulator/mod.rs
  crates/driver/src/infra/simulator/tenderly/mod.rs
  crates/driver/src/infra/solver/mod.rs
  crates/driver/src/main.rs
  crates/driver/src/tests/cases/example_config.rs
  crates/driver/src/tests/cases/quote.rs
  crates/driver/src/tests/cases/settle.rs
  crates/driver/src/tests/cases/solve.rs
  crates/driver/src/tests/setup/blockchain/uniswap.rs
  crates/driver/src/tests/setup/driver.rs
  crates/driver/src/tests/setup/solver.rs
  crates/solver/src/settlement_submission/submitter.rs
  crates/solver/src/settlement_submission/submitter/public_mempool_api.rs
Labels: colocation

#1127 Add documentation for balance_of failure
  crates/shared/src/bad_token/trace_call.rs
Labels: trivial

#1128 Driver API error handling
  crates/driver/src/infra/api/error.rs
  crates/driver/src/infra/api/info.rs
  crates/driver/src/infra/api/mod.rs
  crates/driver/src/infra/api/quote/mod.rs
  crates/driver/src/infra/api/routes/info.rs
  crates/driver/src/infra/api/routes/mod.rs
  crates/driver/src/infra/api/routes/quote/dto/mod.rs
  crates/driver/src/infra/api/routes/quote/dto/order.rs
  crates/driver/src/infra/api/routes/quote/dto/quote.rs
  crates/driver/src/infra/api/routes/quote/mod.rs
  crates/driver/src/infra/api/routes/settle.rs
  crates/driver/src/infra/api/routes/solve/dto/auction.rs
  crates/driver/src/infra/api/routes/solve/dto/mod.rs
  crates/driver/src/infra/api/routes/solve/dto/solution.rs
  crates/driver/src/infra/api/routes/solve/mod.rs
  crates/driver/src/infra/api/settle.rs
  crates/driver/src/infra/api/solve/dto/mod.rs
  crates/driver/src/infra/api/solve/mod.rs
Labels: colocation

#1133 Remove global `#[allow(dead_code)]` in `driver`
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/liquidity/mod.rs
  crates/driver/src/infra/config/file/mod.rs
  crates/driver/src/infra/solver/dto/auction.rs
  crates/driver/src/main.rs
Labels: colocation

#1134 Gracefully handle liquidity errors in `driver`
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/quote.rs
  crates/driver/src/infra/api/error.rs
  crates/driver/src/infra/liquidity/fetcher.rs
Labels: colocation

#1148 Reset Solver Run Outcome Metrics
  crates/solver/src/metrics.rs
Labels: trivial, oncall

#1151 Pass ParaSwap Rate Limiter to Solver
  crates/solver/src/main.rs
  crates/solver/src/solver.rs
Labels: trivial, oncall

#1149 Record Metrics for S3 Uploads
  crates/solver/src/solver/http_solver/instance_cache.rs
Labels: oncall

#1158 Improve Metrics fo Auction Building
  crates/autopilot/src/solvable_orders.rs
Labels: trivial

#1140 SolverRewards: Add score to Settlement
  crates/shared/src/http_solver/model.rs
  crates/solver/src/settlement.rs
Labels: solver rewards

#1169 Remove Unnecessary `#[metrics()]` Attibutes
  crates/autopilot/src/solvable_orders.rs
  crates/shared/src/maintenance.rs
Labels: trivial

#1150 Fix Naive Solver Uniswap Output Rounding
  crates/solver/src/solver/naive_solver.rs
  crates/solver/src/solver/naive_solver/multi_order_solver.rs
Labels: oncall

#1170 Add score to RatedSettlement
  crates/solver/src/driver/solver_settlements.rs
  crates/solver/src/driver_logger.rs
  crates/solver/src/settlement_rater.rs
Labels: solver rewards
