Repository cowprotocol/services, pull requests merged in 2024-08, with the labels that each got.

#2804 Order status API
  crates/database/src/order_events.rs
  crates/e2e/Cargo.toml
  crates/e2e/src/setup/services.rs
  crates/e2e/tests/e2e/order_cancellation.rs
  crates/e2e/tests/e2e/partial_fill.rs
  crates/orderbook/Cargo.toml
  crates/orderbook/openapi.yml
  crates/orderbook/src/api.rs
  crates/orderbook/src/api/get_order_status.rs
  crates/orderbook/src/database/orders.rs
  crates/orderbook/src/dto/order.rs
  crates/orderbook/src/orderbook.rs
Labels: E:6.2 Time to Happy Moo

#2871 Don't send cow amm orders with missing prices
  crates/autopilot/src/solvable_orders.rs
Labels: bug

#2884 Sync run loop to block production
  crates/autopilot/src/arguments.rs
  crates/autopilot/src/boundary/events/settlement.rs
  crates/autopilot/src/database/ethflow_events/event_storing.rs
  crates/autopilot/src/database/onchain_order_events.rs
  crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
  crates/autopilot/src/event_updater.rs
  crates/autopilot/src/infra/blockchain/mod.rs
  crates/autopilot/src/run.rs
  crates/autopilot/src/run_loop.rs
  crates/autopilot/src/shadow.rs
  crates/autopilot/src/solvable_orders.rs
  crates/cow-amm/src/cache.rs
  crates/cow-amm/src/registry.rs
  crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
  crates/driver/src/boundary/liquidity/mod.rs
  crates/driver/src/boundary/liquidity/swapr.rs
  crates/driver/src/boundary/liquidity/uniswap/v2.rs
  crates/driver/src/boundary/liquidity/uniswap/v3.rs
  crates/driver/src/boundary/liquidity/zeroex.rs
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/mempools.rs
  crates/driver/src/infra/blockchain/contracts.rs
  crates/driver/src/infra/blockchain/mod.rs
  crates/driver/src/infra/observe/mod.rs
  crates/driver/src/infra/simulator/enso/mod.rs
  crates/driver/src/infra/tokens.rs
  crates/e2e/tests/e2e/ethflow.rs
  crates/e2e/tests/e2e/quote_verification.rs
  crates/e2e/tests/e2e/refunder.rs
  crates/ethrpc/src/block_stream/mod.rs
  crates/ethrpc/src/lib.rs
  crates/refunder/src/refund_service.rs
  crates/shared/src/account_balances.rs
  crates/shared/src/account_balances/cached.rs
  crates/shared/src/contracts.rs
  crates/shared/src/current_block.rs
  crates/shared/src/event_handling.rs
  crates/shared/src/maintenance.rs
  crates/shared/src/price_estimation/external.rs
  crates/shared/src/price_estimation/factory.rs
  crates/shared/src/price_estimation/native/oneinch.rs
  crates/shared/src/price_estimation/trade_verifier.rs
  crates/shared/src/recent_block_cache.rs
  crates/shared/src/sources/balancer_v2/pool_fetching.rs
  crates/shared/src/sources/balancer_v2/pool_fetching/cache.rs
  crates/shared/src/sources/balancer_v2/pool_fetching/pool_storage.rs
  crates/shared/src/sources/balancer_v2/pool_fetching/registry.rs
  crates/shared/src/sources/uniswap_v2/pool_cache.rs
  crates/shared/src/sources/uniswap_v3/event_fetching.rs
  crates/shared/src/sources/uniswap_v3/pool_fetching.rs
  crates/shared/src/trade_finding/external.rs
  crates/shared/src/zeroex_api.rs
  crates/solver/src/liquidity/zeroex.rs
Labels: E:6.1 One auction per block

#2885 Build auction serially in run loop
  crates/autopilot/src/arguments.rs
  crates/autopilot/src/run.rs
  crates/autopilot/src/run_loop.rs
  crates/autopilot/src/solvable_orders.rs
  crates/ethrpc/src/block_stream/mod.rs
Labels: E:6.1 One auction per block

#2911 Save all auction prices
  crates/autopilot/src/run_loop.rs
Labels: bug

#2915 Detect bad tokens in parallel
  crates/autopilot/src/solvable_orders.rs
Labels: E:6.2 Time to Happy Moo

#2919 Bad token detector maintenance task
  crates/autopilot/src/run.rs
  crates/orderbook/src/run.rs
  crates/shared/src/bad_token/cache.rs
  crates/shared/src/bad_token/list_based.rs
Labels: E:6.2 Time to Happy Moo
