Repository cowprotocol/services, pull requests merged in 2024-05, with the labels that each got.

#2703 [EASY] Authenticator contract available in autopilot
  crates/autopilot/src/infra/blockchain/contracts.rs
Labels: E:7.1 Ext. solvers operating driver

#2724 Calculate score in autopilot domain
  crates/autopilot/src/domain/settlement/mod.rs
  crates/autopilot/src/domain/settlement/trade.rs
Labels: E:7.1 Ext. solvers operating driver

#2725 Move `competition::Solution` to domain
  crates/autopilot/src/domain/competition/mod.rs
  crates/autopilot/src/domain/eth/mod.rs
  crates/autopilot/src/domain/mod.rs
  crates/autopilot/src/run_loop.rs
Labels: E:7.1 Ext. solvers operating driver

#2710 Introduce settlement::Tx
  crates/autopilot/src/domain/eth/mod.rs
  crates/autopilot/src/domain/settlement/mod.rs
  crates/autopilot/src/domain/settlement/transaction.rs
  crates/autopilot/src/infra/blockchain/dto.rs
  crates/autopilot/src/infra/blockchain/mod.rs
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/autopilot/src/run_loop.rs
Labels: E:7.1 Ext. solvers operating driver

#2733 [EASY] Uniform score type
  crates/autopilot/src/domain/competition/mod.rs
  crates/autopilot/src/domain/settlement/mod.rs
  crates/autopilot/src/run_loop.rs
Labels: E:7.1 Ext. solvers operating driver

#2736 DTO conversion for `competition::Solution`
  crates/autopilot/src/domain/competition/mod.rs
  crates/autopilot/src/infra/solvers/dto/solve.rs
  crates/autopilot/src/run_loop.rs
Labels: E:7.1 Ext. solvers operating driver

#2739 Gas estimator driver config
  crates/driver/src/infra/blockchain/gas.rs
  crates/driver/src/infra/config/file/load.rs
  crates/driver/src/infra/config/file/mod.rs
  crates/driver/src/infra/config/mod.rs
  crates/driver/src/run.rs
  crates/driver/src/tests/setup/solver.rs
Labels: E:8.1 Arbitrum One Deployment

#2735 Adjust verified token diffs for settlement contract address
  crates/e2e/tests/e2e/quote_verification.rs
  crates/shared/src/price_estimation/trade_verifier.rs
Labels: E:3.2 Verified Quotes

#2746 Refactor domain::Settlement
  crates/autopilot/src/domain/competition/mod.rs
  crates/autopilot/src/domain/settlement/mod.rs
  crates/autopilot/src/domain/settlement/solution/mod.rs
  crates/autopilot/src/domain/settlement/solution/tokenized.rs
  crates/autopilot/src/domain/settlement/solution/trade.rs
  crates/autopilot/src/domain/settlement/tokenized.rs
  crates/autopilot/src/domain/settlement/transaction.rs
  crates/autopilot/src/infra/blockchain/dto.rs
  crates/autopilot/src/infra/blockchain/mod.rs
  crates/autopilot/src/on_settlement_event_updater.rs
  crates/autopilot/src/run_loop.rs
Labels: E:7.1 Ext. solvers operating driver

#2748 Create auction orders table
  crates/autopilot/src/database/competition.rs
  crates/database/src/auction_orders.rs
  crates/database/src/lib.rs
  database/README.md
  database/sql/V065__auction_orders.sql
Labels: E:7.1 Ext. solvers operating driver

#2705 Circuit breaker remove solver
  crates/autopilot/src/infra/blockchain/authenticator.rs
  crates/autopilot/src/infra/blockchain/contracts.rs
  crates/autopilot/src/infra/blockchain/mod.rs
  crates/autopilot/src/run.rs
  crates/contracts/artifacts/Roles.json
  crates/contracts/build.rs
  crates/contracts/src/lib.rs
Labels: E:7.1 Ext. solvers operating driver
