Repository cowprotocol/services, pull requests merged in 2024-03, with the labels that each got.

#2463 Metric for token list update
  crates/shared/src/token_list.rs
Labels: oncall

#2490 Polish scoring native functions
  crates/driver/src/domain/competition/solution/scoring.rs
Labels: E:4.5 Rank By Suplus

#2497 Volume based protocol fee for scoring
  crates/driver/src/domain/competition/solution/scoring.rs
Labels: E:4.4 Protocol fee based on Volume

#2523 [EASY] Separate log for disabled mempool
  crates/driver/src/infra/observe/mod.rs
Labels: oncall

#2531 [EASY] Fix surplus scoring error
  crates/driver/src/domain/competition/solution/scoring.rs
Labels: E:4.5 Rank By Suplus

#2518 Add log for fetched events
  crates/shared/src/event_handling.rs
Labels: oncall

#2545 Forbit fee policies with factor 1.0
  crates/autopilot/src/arguments.rs
  crates/e2e/tests/e2e/protocol_fee.rs
Labels: E:4.2 Protocol Fee Implementation, E:4.3 Protocol Fee PriceImprovement over Quote, E:4.4 Protocol fee based on Volume

#2535 Adjust order limit prices for volume based fee
  crates/driver/src/infra/solver/dto/auction.rs
  crates/driver/src/tests/cases/protocol_fees.rs
  crates/driver/src/tests/setup/solver.rs
Labels: E:4.4 Protocol fee based on Volume

#2566 [EASY] Fix ceil_div in scoring
  crates/driver/src/domain/competition/solution/mod.rs
Labels: E:4.5 Rank By Suplus

#2527 [Easy] Remove boundary submission logic
  crates/driver/src/boundary/mempool.rs
  crates/driver/src/boundary/mod.rs
  crates/driver/src/domain/mempools.rs
  crates/driver/src/infra/config/file/load.rs
  crates/driver/src/infra/config/file/mod.rs
  crates/driver/src/infra/mempool/mod.rs
  crates/driver/src/run.rs
  crates/driver/src/tests/setup/driver.rs
  crates/driver/src/tests/setup/solver.rs
  crates/e2e/src/setup/colocation.rs
Labels: stale

#2567 Fix price improvement fee when scoring
  crates/driver/src/domain/competition/solution/mod.rs
  crates/driver/src/domain/competition/solution/scoring.rs
  crates/driver/src/tests/cases/protocol_fees.rs
Labels: E:4.3 Protocol Fee PriceImprovement over Quote

#2504 Autopilot surplus calculation
  crates/autopilot/src/domain/auction/mod.rs
  crates/autopilot/src/domain/auction/order.rs
  crates/autopilot/src/domain/eth/mod.rs
  crates/autopilot/src/domain/settlement/mod.rs
  crates/autopilot/src/domain/settlement/trade.rs
  crates/autopilot/src/util/conv.rs
  crates/autopilot/src/util/mod.rs
  crates/driver/src/domain/competition/auction.rs
  crates/driver/src/domain/competition/solution/scoring.rs
  crates/driver/src/domain/eth/mod.rs
Labels: E:4.5 Rank By Suplus

#2572 Fix quote fee handling in market price
  crates/autopilot/src/domain/fee/mod.rs
  crates/database/src/orders.rs
  crates/driver/src/domain/competition/solution/fee.rs
  crates/driver/src/tests/cases/protocol_fees.rs
  crates/e2e/tests/e2e/protocol_fee.rs
  crates/orderbook/src/database/orders.rs
  crates/shared/src/order_validation.rs
Labels: E:4.3 Protocol Fee PriceImprovement over Quote

#2577 [EASY] Remove score cap
  crates/autopilot/src/arguments.rs
  crates/autopilot/src/infra/solvers/dto/solve.rs
  crates/autopilot/src/run.rs
  crates/autopilot/src/run_loop.rs
  crates/autopilot/src/shadow.rs
  crates/driver/openapi.yml
  crates/driver/src/domain/competition/auction.rs
  crates/driver/src/domain/competition/solution/settlement.rs
  crates/driver/src/domain/quote.rs
  crates/driver/src/infra/api/routes/solve/dto/auction.rs
  crates/driver/src/tests/cases/mod.rs
  crates/driver/src/tests/setup/driver.rs
Labels: E:4.5 Rank By Suplus
