Repository cowprotocol/services, pull requests merged in 2025-08, with the labels that each got.

#3489 Remove deprecated single winner auction logic
  crates/autopilot/src/arguments.rs
  crates/autopilot/src/database/competition.rs
  crates/autopilot/src/domain/competition/winner_selection.rs
  crates/autopilot/src/domain/competition/winner_selection/max_score.rs
  crates/autopilot/src/domain/competition/winner_selection/mod.rs
  crates/autopilot/src/run.rs
  crates/autopilot/src/run_loop.rs
  crates/autopilot/src/shadow.rs
  crates/e2e/tests/e2e/database.rs
  crates/e2e/tests/e2e/limit_orders.rs
  crates/e2e/tests/e2e/solver_competition.rs
  crates/e2e/tests/e2e/univ2.rs
Labels: stale

#3544 Revert "Parallelize data fetching tasks in the driver (#3450)"
  crates/driver/src/domain/competition/auction.rs
  crates/driver/src/domain/competition/mod.rs
  crates/driver/src/domain/competition/pre_processing.rs
  crates/driver/src/domain/competition/sorting.rs
  crates/driver/src/infra/api/mod.rs
  crates/driver/src/infra/api/routes/solve/mod.rs
  crates/driver/src/infra/observe/metrics.rs
Labels: hotfix

#3582 EthFlow setup for the playground
  playground/.env.example
  playground/README.md
  playground/docker-compose.fork.yml
  playground/test_playground.sh
Labels: documentation

#3589 Remove test-specific commands from README
  README.md
Labels: documentation
